draft-kuehlewind-shmoo-remote-fee.md
Proposed rewording of sentence about remove of free option with online meetings
=> Comment by Brian Carpenter

draft-kuehlewind-shmoo-remote-fee.md
modest suggestions for consideration. These are comments as an individual. I do not feel strongly about any of the changes - just for consideration. :-)
=> Proposed changes to # Financial impact

draft-ietf-shmoo-remote-fee.md
As discussed with Brian Carpenter on list
=> Sentence of responsibility of LLC

draft-ietf-shmoo-remote-fee.md
Based on initial suggestion by Rich Salz on list.
=> Proposal by Charles Eckel to note related events

draft-kuehlewind-shmoo-remote-fee.md
Some modest suggestions for draft-kuehlewind-shmoo-remote-fee
=> Some suggested edits to intro

draft-ietf-shmoo-remote-fee.md
We can merge this with the next version after IESG review.
=> Unify capitalisation

draft-ietf-shmoo-remote-fee.md
@richsalz @jdreed Are there others we should name here explicitly?
=> Adding Lars to the Acks

draft-ietf-shmoo-remote-fee.md
Add "nothing to see here" to appease idnits; found by Suresh.
=> Add boilerplate sections

draft-ietf-shmoo-remote-fee.md
=> Comment John/Barry

draft-ietf-shmoo-remote-fee.md
Thanks to Eric Vyncke to flag this oversight in this IESG review!
=> remove oversight of last use of "fully online meeting"

draft-ietf-shmoo-remote-fee.md
Thanks to John Scudder for this feedback in IESG review!
=> remove "always" in abstract and principle sec

draft-ietf-shmoo-remote-fee.md
Emphasize principle vs mechanism.
=> Attempt to address Scudder's concern

draft-ietf-shmoo-remote-fee.md
Thanks for the feedback during IESG review
=> Editorial comment by Roman Danyliw

draft-ietf-shmoo-remote-fee.md
Thanks to Francesca in her IESG review!
=> Remove observer reference as unnecessary/undefined (addresses point 1 from Francesca's discuss)

draft-ietf-shmoo-remote-fee.md
This PR aims to address, at least partially, feedback by John Klensin and Francesca Palombimi. However, we should probably check with the working group if there is consensus to add these additional requirements on the LLC.
=> PII confidentiality and transparency of implementation (addresses point 2 from Francesca's discuss)

draft-ietf-shmoo-remote-fee.md
=> Clarify LLC responsibilities (addresses point 3 from Francesca's discuss)

draft-ietf-shmoo-remote-fee.md
As an attempt to address concerns raised by Jay Daley...
=> Refinement on the text about costs

draft-ietf-shmoo-remote-fee.md
=> nit on rfc8711

draft-ietf-shmoo-remote-fee.md
=> nits by John Scudder

draft-ietf-shmoo-remote-fee.md
=> Editorial change proposed by Rob Wilton
